### ISSUE TITLE
Edit Travis config

### ISSUE THREAD

**Issue by lcolladotor** [carriewright11/ttester#1]
Hi Carrie,

You copy-pasted the Travis to Slack config line from one of my repos, so I'm getting notifications about your package Travis' builds on a Slack channel of mine. Can you edit/delete https://github.com/carriewright11/ttester/blob/master/.travis.yml#L21 ?

Thanks,
Leo

**Comment by carriewright11** [comment]
Done! sorry about that! - also don't know how I missed this for so long
